services:
    nginx:
      build: ./requirements/nginx/.
      container_name: nginx
      ports:
        - "443:443"
      volumes:
        - ./../secrets/nginx.crt:/etc/nginx/ssl/nginx.crt:ro
        - ./../secrets/nginx.key:/etc/nginx/ssl/nginx.key:ro
        - /home/matvejg/Inception/wp-db:/var/www/html
      networks:
        - inception
      depends_on:
        - wordpress
      restart: always
    wordpress:
      build: ./requirements/wordpress/.
      container_name: wordpress
      environment:
        - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}:3306
        - WORDPRESS_DB_NAME=${WP_DB_NAME}
        - WORDPRESS_DB_USER=${WP_DB_USER}
        - WORDPRESS_ADMIN_USER=${WP_ADMIN_USER}
        - WORDPRESS_USER=${WP_USER}
        - DOMAIN_NAME=${DOMAIN_NAME}
      secrets:
        - db_password
        - wp_root_password
        - wp_user_password
      volumes:
        - /home/matvejg/Inception/wp-db:/var/www/html
      networks:
        - inception
      depends_on:
        - mariadb
      restart: always
    mariadb:
      build: ./requirements/mariadb/.
      container_name: mariadb
      environment:
        - MARIADB_DATABASE=${WP_DB_NAME}
        - MARIADB_USER=${WP_DB_USER}
      secrets:
        - db_password
      volumes:
        - /home/matvejg/Inception/db:/var/lib/mysql
      networks:
        - inception
      restart: always

networks:
  inception:
    driver: bridge

secrets:
  wp_root_password:
    file: ./../secrets/wp_root_password.txt
  wp_user_password:
    file: ./../secrets/wp_user_password.txt
  db_password:
    file: ./../secrets/db_password.txt