services:
    nginx:
      build: ./requirements/nginx/.
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      user: "${UID}:${GID}"
      volumes:
        - ./web:/var/www/html
    wordpress:
      build: ./requirements/wordpress/.
      container_name: wp-php
      user: "${UID}:${GID}"
      volumes:
        - ./web:/var/www/html