version: '3.8'

services:
    nginx:
        image: nginx:latest
        ports:
        - "80:80"
        - "443:443"
    wordpress:
      build: ./requirements/wordpress/.
      container_name: wp-php